/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
}

group = "canaryprism.mcwm"
version = "2.5.0"
description = "MCWorldManager"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(22)
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    api(libs.com.formdev.flatlaf)
    api(libs.org.apache.commons.commons.compress)
    api(libs.org.apache.commons.commons.text)
    api(libs.com.github.querz.nbt)
    api(libs.org.json.json)
    api(libs.dev.dirs.directories)
    testImplementation(libs.junit.junit)
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
