import java.util.stream.Collectors

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    id("com.gradleup.shadow") version "8.3.5"
}

group = "canaryprism.mcwm"
version = "3.0.1"
description = "Minecraft World Manager"

application {
    mainModule = "canaryprism.mcwm"
    mainClass = "canaryprism.mcwm.Main"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(22)
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)

    implementation(libs.flatlaf)
    implementation(libs.commons.text)
    implementation(libs.commons.io)
    implementation(libs.commons.configuration2)
    implementation(libs.querz.nbt)
    implementation(libs.org.json.json)

    implementation(libs.directories)

    runtimeOnly(libs.vfs2nio)
}


tasks.register<Copy>("gatherJars") {
    notCompatibleWithConfigurationCache("i don't really know")
    dependsOn(tasks.jar)
    into("build/release")
    from(configurations.runtimeClasspath, tasks.jar.get().archiveFile.get())
}

tasks.register("writeJPackageArgs") {
    notCompatibleWithConfigurationCache("i don't really know")
    dependsOn(tasks.jar)
    doLast {
        file("icon.png").copyTo(file("build/release/icon.png"), true)
        val file = file("build/release/args")
        file.writeText("""
            -n "${project.name}"
            --description "${project.description}"
            -p "${(configurations.runtimeClasspath.get().files + setOf(tasks.jar.get().archiveFile.get().asFile))
            .stream().map { it.name }.collect(Collectors.joining(File.pathSeparator))}"
            -m "${application.mainModule.get()}/${application.mainClass.get()}"
            --app-version "${project.version}"
            --icon "icon.png"
        """.trimIndent())
    }
}

tasks.register("writeInfo") {
    notCompatibleWithConfigurationCache("i don't really know")
    doLast {
        val file = file("build/release/info.env")
        file.writeText("""
            NAME=${project.name}
            VERSION=${project.version}
        """.trimIndent())
    }
}

tasks.register("release") {
    notCompatibleWithConfigurationCache("i don't really know")
    dependsOn(tasks["gatherJars"], tasks["writeJPackageArgs"], tasks["writeInfo"])
}

tasks.shadowJar {
    mergeServiceFiles()
}

tasks.test {
    useJUnitPlatform()
}